---
title: "Hello, world."
description: "A more formal introduction to this corner of the internet I’ve rebuilt (again)."
date: "1/15/2025"
categories: ['personal']
draft: true
---

# Why is this post here?

As a high school student in the San Francisco Bay Area, I found solace in creative expression. My small Tumblr blog became a haven for poems and literary snippets, while DeviantArt showcased photographs and sketches inspired by Caltrain and BART adventures to “the City.” Despite the typical teenage melancholy—grappling with an uncertain personal future amid global events such as the 2010 Arab Spring and Occupy Protests[^1]—these artistic outlets brought me joy. 

[^1]: For those interested in what was going on around this time in San Francisco, I’ve dug up two few articles. One about the [protests at the Civic Center BART Station](https://www.truthdig.com/articles/san-francisco-bay-areas-bart-pulls-a-mubarak/) following the shooting of Charles Blair Hill by BART police, and another about [Occupy SF](https://www.cbsnews.com/sanfrancisco/news/demonstrators-fill-downtown-sf-in-solidarity-with-occupy-wall-street-protests/), a movement held in solidarity with [Occupy Wall Street](https://www.history.com/this-day-in-history/occupy-wall-street-begins-zuccotti-park) to protest the widening gap between rich and poor. As a young student taking “Cultural World History” at the time, we followed these events (and others) closely and even participated in some cases.

However, my creative pursuits came to an abrupt halt when I began my Bioengineering degree at the University of California, San Diego (UCSD) in 2013. Immersed in scientific research and extracurriculars, I couldn’t fathom picking up my DSLR or gouache paints while drowning in programming assignments, mandatory quizzes, and extracurricular activities.

Over the years, I’ve yearned for that creative spark and a tangible space to share my voice.

Enter my New Year’s Goal (“resolution” feels too much like an assignment) to express myself more. What better way than to revive my blogging habit? I envision this space as an intermittent internet scrapbook of thoughts and musings, not necessarily limited to science. Who knows? I might even dust off Affinity Designer or Procreate to post some artwork here eventually! So, welcome to this revamped website! 

To kick off the festivities, I wanted to share my background and how it has shaped my worldview today. I hope you’ll find this little tidbit at least somewhat interesting!

# Navigating education as a first-generation Filipino American

Growing up as a first-generation Filipino American in a multi-generational household quickly internalized the notion that attending an American college was the golden yellow brick road to prosperity in the States. After meeting each other in the United States, my immigrant parents—despite having completed bachelor’s degrees in the Philippines (PH) amid the Marcos Regime[^2]—found themselves constantly struggling to prove their competence to employers. Their professional experiences etched into my young mind the stark reality of the challenges faced by foreign-educated professionals in the American job market.

[^2]: My parents were students during [the People Power Revolution of 1986 in the Philippines](https://en.wikipedia.org/wiki/Student_activism_in_the_Philippines_(1965%E2%80%931972))—a time of martial law under former President Ferdinand Marcos’ regime when the country was under financial hardship.

My father’s path to the United States began by following his older brother into the US Military–my uncle was a US Navy Man whilst my father enlisted in the US Marines. After completing his service, my father faced the daunting task of reintegrating into civilian life—which meant completely redoing his Mechanical Engineering undergraduate education stateside while working full-time. For nearly a decade, he juggled part-time classes at both state and community colleges; a demanding career that required traveling as a satellite integration and test engineer; and raising a young child (me!). Despite his extensive work experience, he was repeatedly overlooked for raises and job advancements due to his “subpar” foreign certifications. Finally, after almost a decade of perseverance, he earned his all American bachelor’s degree—a momentous accomplishment that came at the cost of countless missed opportunities that would have helped our growing family.

On the other hand, my mother came to the United States for a better life after being petitioned by my grandfather, an electrical engineer for the US Navy, as part of a special family visa. Despite finishing her accounting degree in the Philippines, she struggled to find an employer that would hire her without having the Certified Public Accountant (CPA) certification. This catch-22 situation left my mother in a precarious but unfortunately familiar position for many immigrants—overqualified for entry-level positions but unable to secure jobs matching her education and experience. Luckily, she was eventually able to find an employer willing to take her and help her build her career; she’s since stayed within the same network of people.

Watching my parents have these experiences fed into what felt like an accompaniment to the daily prayer I did as a Catholic-raised child, “Your (American, or Western) education will keep you safe.” 

However, this mantra came with a bittersweet caveat. This prayer was a corollary: education is expensive and requires money, money we didn’t necessarily have an abundance of.

The stark reality of our financial limitations became increasingly apparent in middle school. I watched friends regularly attend club sports like lacrosse or volleyball, science summer camps with NASA alumni, and private tutoring for higher grades. The pressure of not having enough pushed me to seek alternatives. I eventually found solace at my local library, in my non-white community, and eventually in online spaces–for at least those were accessible. I spent my days on MSN Messenger, AIM, and Tumblr, connecting with anonymous strangers who luckily turned out to be kind people I still chat with occasionally. In between sending each other virtual letters and mixtapes filled with songs ripped off Limewire and Youtube, we helped each other with homework, filing FAFSA documents, and talked about our anxieties for the future.

Online, I found an identity and a semblance of peace–a stark contrast to my real life where I often faded into the background of my bustling multi-generational, multi-family household. Digital spaces offered a sense of control over my future and a welcoming community where I could freely ask about educational opportunities and college requirements unfamiliar to my family, without fear of judgement or repercussions.

# Reflections and aspirations for the future

Now, as the second in my family after my paternal grandmother to earn a terminal degree, I recognize how profoundly my childhood has shaped my worldview.

The struggles and resilience of my immigrant parents instilled in me a deep appreciation for education’s transformative power. But it also made abundantly clear the importance of making those opportunities accessible for people of all backgrounds. While perseverance in the face of systemic barriers is often lauded in minoritized individuals, I feel it is equally crucial to provide these individuals with opportunities for rest and support. 

Next, experiencing the rapid gentrification of my San Francisco Bay Area neighborhood and navigating socioeconomic differences between peers sharpened my awareness of educational disparities. While I was fortunate to have stumbled upon supportive online communities, such resources aren’t universally available. As a scientist who now has the means to give back, I feel that I’ll forever dedicate my life towards always helping others avoid the isolation I once experienced.

All in all, behind every student and scientist is a unique story of challenges and aspirations. As a Filipina in STEM, I’m dedicated to fostering environments where all individuals can thrive and contribute their perspectives, regardless of background. With this blog, I hope to not only share more of my background and experiences, but also post things that might help others that are interested in STEM! 
